import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { BriefcaseBusiness, Users, WalletCards, AlertTriangle } from "lucide-react";
import { supabaseServices } from "@/lib/services";
import { useProjectPermissions } from "@/hooks/useProjects";
import { ModuleHeader } from "@/components/admin/ModuleHeader";
import { MetricCard } from "@/components/admin/MetricCard";
import { KpiGrid } from "@/components/admin/KpiGrid";
import { SectionCard } from "@/components/admin/SectionCard";
import { EmptyState } from "@/components/admin/EmptyState";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

const label = (value: string | null) => ({ requested: "Solicitado", published: "Publicado", accepted: "Aceptado", en_route: "En camino", pickup: "Recogida", in_progress: "En curso", completed: "Completado", settled: "Liquidado", cancelled_by_customer: "Cancelado por cliente", cancelled_by_driver: "Cancelado por conductor", expired: "Expirado", incident: "Incidencia", confirmed: "Confirmada", rejected: "Rechazada", reconciled: "Conciliada", incomplete: "Incompleto", pending_topup: "Pendiente", active: "Activo", suspended: "Suspendido", trial_free: "Gratis", wallet_commission: "Billetera", passenger: "Pasajeros", cargo: "Carga", courier: "Mensajería", tourism: "Turismo" }[value ?? ""] ?? value ?? "—");
const message = (error: unknown) => error instanceof Error ? ({ INITIAL_MINIMUM_DEPOSIT_REQUIRED: "El primer depósito debe alcanzar el mínimo configurado.", RESOLUTION_NOTE_REQUIRED: "La nota de resolución es obligatoria.", SUSPENSION_REASON_REQUIRED: "El motivo es obligatorio.", JOB_NOT_IN_INCIDENT: "El trabajo ya no está en incidencia." }[error.message] ?? error.message) : "No se pudo completar la operación.";

export default function MarketplaceSection({ projectId }: { projectId: string }) {
  const { data: permissions = [] } = useProjectPermissions(projectId);
  const [tab, setTab] = useState("resumen");
  const [selectedJob, setSelectedJob] = useState<string | null>(null); const [driver, setDriver] = useState<{ id: string; suspended: boolean } | null>(null); const [reason, setReason] = useState(""); const [incident, setIncident] = useState<string | null>(null); const [resolution, setResolution] = useState<"completed" | "cancelled">("completed"); const [error, setError] = useState<string | null>(null); const queryClient = useQueryClient();
  const canCustomers = permissions.includes("customers.view"); const canPayments = permissions.includes("payments.view"); const canManagePayments = permissions.includes("payments.manage"); const canSettings = permissions.includes("settings.view"); const canManageSettings = permissions.includes("settings.manage"); const canManageMarketplace = permissions.includes("marketplace.manage");
  const overview = useQuery({ queryKey: ["marketplace-overview", projectId], queryFn: () => supabaseServices.marketplace.overview(projectId), refetchInterval: 30_000 });
  const jobs = useQuery({ queryKey: ["marketplace-jobs", projectId], queryFn: () => supabaseServices.marketplace.listJobs(projectId), enabled: tab === "trabajos" });
  const drivers = useQuery({ queryKey: ["marketplace-drivers", projectId], queryFn: () => supabaseServices.marketplace.listDrivers(projectId), enabled: tab === "conductores" });
  const customers = useQuery({ queryKey: ["marketplace-customers", projectId], queryFn: () => supabaseServices.marketplace.listCustomers(projectId), enabled: tab === "clientes" && canCustomers });
  const wallets = useQuery({ queryKey: ["marketplace-wallets", projectId], queryFn: () => supabaseServices.marketplace.listWallets(projectId), enabled: tab === "billeteras" && canPayments });
  const topups = useQuery({ queryKey: ["marketplace-topups", projectId], queryFn: () => supabaseServices.marketplace.listTopups(projectId), enabled: tab === "recargas" && canPayments });
  const incidents = useQuery({ queryKey: ["marketplace-incidents", projectId], queryFn: () => supabaseServices.marketplace.listIncidents(projectId), enabled: tab === "incidencias" });
  const settings = useQuery({ queryKey: ["marketplace-financial-settings", projectId], queryFn: () => supabaseServices.marketplace.financialSettings(projectId), enabled: tab === "configuracion" && canSettings });
  const detail = useQuery({ queryKey: ["marketplace-job-detail", projectId, selectedJob], queryFn: () => supabaseServices.marketplace.getJobDetail(projectId, selectedJob!), enabled: !!selectedJob });
  const invalidate = (...keys: string[]) => Promise.all(keys.map(key => queryClient.invalidateQueries({ queryKey: [key, projectId] })));
  const suspend = useMutation({ mutationFn: () => supabaseServices.marketplace.setDriverSuspension(projectId, { userId: driver!.id, suspended: driver!.suspended, reason }), onSuccess: () => { setDriver(null); setReason(""); void invalidate("marketplace-overview", "marketplace-drivers", "marketplace-jobs", "marketplace-incidents"); }, onError: e => setError(message(e)) });
  const resolve = useMutation({ mutationFn: () => supabaseServices.marketplace.resolveIncident(projectId, { jobId: incident!, resolution, note: reason, idempotencyKey: crypto.randomUUID() }), onSuccess: () => { setIncident(null); setReason(""); void invalidate("marketplace-overview", "marketplace-jobs", "marketplace-drivers", "marketplace-incidents", "marketplace-wallets"); }, onError: e => setError(message(e)) });
  const data = overview.data;
  return <div className="space-y-5 sm:space-y-6"><ModuleHeader title="Trabajos" description="Operación de TukTuk Marketplace." icon={BriefcaseBusiness} module="pagos" />
    <Tabs value={tab} onValueChange={setTab}><TabsList className="h-auto w-full flex-wrap justify-start"><TabsTrigger value="resumen">Resumen</TabsTrigger><TabsTrigger value="trabajos">Trabajos</TabsTrigger><TabsTrigger value="conductores">Conductores</TabsTrigger>{canCustomers && <TabsTrigger value="clientes">Clientes</TabsTrigger>}{canPayments && <><TabsTrigger value="billeteras">Billeteras</TabsTrigger><TabsTrigger value="recargas">Recargas</TabsTrigger></>}<TabsTrigger value="incidencias">Incidencias</TabsTrigger>{canSettings && <TabsTrigger value="configuracion">Configuración</TabsTrigger>}</TabsList>
      <TabsContent value="resumen"><KpiGrid columns={4} density="compact"><MetricCard label="Conductores" value={data?.driversTotal ?? 0} icon={Users} module="pagos" isLoading={overview.isLoading}/><MetricCard label="Activos" value={data?.driversActive ?? 0} icon={Users} module="pagos"/><MetricCard label="En prueba" value={data?.driversTrialActive ?? 0} icon={BriefcaseBusiness} module="pagos"/><MetricCard label="Post-prueba activos" value={data?.driversPostTrialActive ?? 0} icon={WalletCards} module="pagos"/><MetricCard label="Trabajos publicados" value={data?.jobsPublished ?? 0} icon={BriefcaseBusiness} module="pagos"/><MetricCard label="Trabajos activos" value={data?.jobsActive ?? 0} icon={BriefcaseBusiness} module="pagos"/><MetricCard label="Incidencias abiertas" value={data?.jobsIncidentOpen ?? 0} icon={AlertTriangle} module="pagos"/>{data?.pendingTopups !== null && <MetricCard label="Recargas pendientes" value={data?.pendingTopups ?? 0} icon={WalletCards} module="pagos"/>}</KpiGrid></TabsContent>
      <TabsContent value="trabajos"><List title="Trabajos" loading={jobs.isLoading} isEmpty={!jobs.data?.length} empty="No hay trabajos.">{jobs.data?.map(x=><Row key={x.jobId} title={`${x.originText} → ${x.destinationText}`} detail={`${label(x.status)} · ${label(x.serviceCode)} · ${x.finalPrice} ${x.currency}${x.driverDisplayName ? ` · ${x.driverDisplayName}` : ""}`} action={<Button size="sm" variant="outline" onClick={() => setSelectedJob(x.jobId)}>Ver detalle</Button>}/>)}</List></TabsContent>
      <TabsContent value="conductores"><List title="Conductores" loading={drivers.isLoading} isEmpty={!drivers.data?.length} empty="No hay conductores.">{drivers.data?.map(x=><Row key={x.userId} title={x.displayName} detail={`${x.phone ?? "Sin WhatsApp"} · ${label(x.status)} · ${x.trialActive ? "En prueba" : "Sin prueba"} · ${x.vehicleName ?? "Sin vehículo"} · ${x.isAvailable ? "Disponible" : "No disponible"}`} action={canManageMarketplace ? <Button size="sm" variant="outline" onClick={() => setDriver({ id:x.userId, suspended:x.status !== "suspended" })}>{x.status === "suspended" ? "Reactivar" : "Suspender"}</Button> : undefined}/>)}</List></TabsContent>
      {canCustomers && <TabsContent value="clientes"><List title="Clientes" loading={customers.isLoading} isEmpty={!customers.data?.length} empty="No hay clientes.">{customers.data?.map(x=><Row key={x.customerId} title={x.displayName} detail={`${x.whatsappPhone} · ${x.jobsTotal} trabajos · ${x.jobsActive} activos · ${x.jobsSettled} liquidados`}/>)}</List></TabsContent>}
      {canPayments && <><TabsContent value="billeteras"><List title="Billeteras" loading={wallets.isLoading} isEmpty={!wallets.data?.length} empty="No hay billeteras.">{wallets.data?.map(x=><Row key={x.userId} title={x.driverDisplayName} detail={`${x.totalBalance} total · ${x.reservedBalance} reservado · ${x.availableBalance} ${x.currency} disponible`}/>)}</List></TabsContent><TabsContent value="recargas"><List title="Recargas" loading={topups.isLoading} isEmpty={!topups.data?.length} empty="No hay recargas.">{topups.data?.map(x=><Row key={x.topupId} title={x.driverDisplayName} detail={`${x.amount} ${x.currency} · ${label(x.status)}`} action={canManagePayments && x.status === "requested" ? <Button size="sm">Gestionar</Button> : undefined}/>)}</List></TabsContent></>}
      <TabsContent value="incidencias"><List title="Incidencias" loading={incidents.isLoading} isEmpty={!incidents.data?.length} empty="No hay incidencias.">{incidents.data?.map(x=><Row key={x.jobId} title={label(x.serviceCode)} detail={`${x.incidentReason} · ${x.resolved ? "Resuelta" : "Abierta"}`} action={canManageMarketplace && !x.resolved ? <Button size="sm" variant="outline" onClick={() => setIncident(x.jobId)}>Resolver</Button> : undefined}/>)}</List></TabsContent>
      {canSettings && <TabsContent value="configuracion"><SectionCard title="Configuración financiera" module="pagos"><p className="text-sm text-text-secondary">Moneda: {settings.data?.walletCurrency ?? "CUP"} · Depósito mínimo: {settings.data?.initialMinimumDeposit ?? "—"} · Comisión: {settings.data ? `${settings.data.commissionRate * 100}%` : "—"}</p></SectionCard></TabsContent>}
    </Tabs>{error && <p className="text-sm text-destructive">{error}</p>}<Dialog open={!!selectedJob} onOpenChange={() => setSelectedJob(null)}><DialogContent><DialogHeader><DialogTitle>Detalle del trabajo</DialogTitle></DialogHeader>{detail.isLoading ? "Cargando…" : detail.data ? <div className="space-y-3 text-sm"><p><b>Estado:</b> {String(detail.data.job.status ?? "—")}</p><p><b>Ruta:</b> {String(detail.data.serviceRequest.origin_text ?? "—")} → {String(detail.data.serviceRequest.destination_text ?? "—")}</p>{detail.data.customer && <p><b>Cliente:</b> {String(detail.data.customer.display_name ?? "—")}</p>}<p><b>Eventos:</b> {detail.data.timeline.length}</p>{detail.data.financial && <p><b>Finanzas:</b> información disponible.</p>}</div> : null}</DialogContent></Dialog><Dialog open={!!driver} onOpenChange={() => setDriver(null)}><DialogContent><DialogHeader><DialogTitle>{driver?.suspended ? "Suspender conductor" : "Reactivar conductor"}</DialogTitle></DialogHeader>{driver?.suspended && <Textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="Motivo obligatorio"/>}<Button disabled={suspend.isPending || (driver?.suspended && !reason.trim())} onClick={() => suspend.mutate()}>{driver?.suspended ? "Suspender" : "Confirmar reactivación"}</Button></DialogContent></Dialog><Dialog open={!!incident} onOpenChange={() => setIncident(null)}><DialogContent><DialogHeader><DialogTitle>Resolver incidencia</DialogTitle></DialogHeader><div className="flex gap-2"><Button variant={resolution === "completed" ? "default" : "outline"} onClick={()=>setResolution("completed")}>Completar</Button><Button variant={resolution === "cancelled" ? "default" : "outline"} onClick={()=>setResolution("cancelled")}>Cancelar</Button></div><Textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="Motivo / nota de resolución"/><p className="text-xs text-text-secondary">{resolution === "completed" ? "Confirma el trabajo y aplica la comisión correspondiente cuando proceda." : "Cancela administrativamente el resultado. Si una comisión ya fue cobrada, el sistema realizará la reversión correspondiente."}</p><Button disabled={resolve.isPending || !reason.trim()} onClick={() => resolve.mutate()}>Resolver</Button></DialogContent></Dialog></div>;
}
function List({ title, loading, isEmpty, empty, children }: { title: string; loading: boolean; isEmpty: boolean; empty: string; children: React.ReactNode }) { return <SectionCard title={title} module="pagos" contentClassName="space-y-2">{loading ? <p className="text-sm text-text-tertiary">Cargando…</p> : isEmpty ? <EmptyState icon={BriefcaseBusiness} title={empty} module="pagos" /> : children}</SectionCard>; }
function Row({ title, detail, action }: { title: string; detail: string; action?: React.ReactNode }) { return <div className="flex items-center justify-between gap-3 rounded border border-border-subtle p-3"><div><p className="font-medium text-text-primary">{title}</p><p className="text-sm text-text-secondary">{detail}</p></div>{action ?? <Badge variant="secondary">—</Badge>}</div>; }
