import { useEffect, useMemo, useState } from "react";
import { useInfiniteQuery, useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AlertTriangle, BriefcaseBusiness, Users, WalletCards } from "lucide-react";
import { supabaseServices } from "@/lib/services";
import { useProjectPermissions } from "@/hooks/useProjects";
import { ModuleHeader } from "@/components/admin/ModuleHeader";
import { MetricCard } from "@/components/admin/MetricCard";
import { KpiGrid } from "@/components/admin/KpiGrid";
import { SectionCard } from "@/components/admin/SectionCard";
import { EmptyState } from "@/components/admin/EmptyState";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

const PAGE_SIZE = 25;
const label = (v: string | null) => ({ requested:"Solicitado",published:"Publicado",accepted:"Aceptado",en_route:"En camino",pickup:"Recogida",in_progress:"En curso",completed:"Completado",settled:"Liquidado",incident:"Incidencia",expired:"Expirado",confirmed:"Confirmada",rejected:"Rechazada",active:"Activo",suspended:"Suspendido",passenger:"Pasajeros",cargo:"Carga",courier:"Mensajería",tourism:"Turismo",wallet_commission:"Billetera" }[v ?? ""] ?? v ?? "—");
const text = (v: unknown) => v == null || v === "" ? "—" : String(v);
const errorText = (e: unknown) => e instanceof Error ? ({ INITIAL_MINIMUM_DEPOSIT_REQUIRED:"El primer depósito debe alcanzar el mínimo configurado.",RESOLUTION_NOTE_REQUIRED:"La nota de resolución es obligatoria.",SUSPENSION_REASON_REQUIRED:"El motivo es obligatorio.",JOB_NOT_IN_INCIDENT:"El trabajo ya no está en incidencia." }[e.message] ?? e.message) : "No se pudo completar la operación.";
const rows = <T,>(q: { data?: { pages: Array<{items:T[]}> } }) => q.data?.pages.flatMap(x => x.items) ?? [];

export default function MarketplaceSection({ projectId }: { projectId: string }) {
  const { data: permissions = [] } = useProjectPermissions(projectId);
  const [tab,setTab]=useState("resumen"),[status,setStatus]=useState(""),[service,setService]=useState(""),[incidentState,setIncidentState]=useState("open");
  const [jobId,setJobId]=useState<string|null>(null),[driver,setDriver]=useState<{id:string;suspended:boolean}|null>(null),[incident,setIncident]=useState<string|null>(null),[reason,setReason]=useState(""),[resolution,setResolution]=useState<"completed"|"cancelled">("completed"),[error,setError]=useState<string|null>(null);
  const [topup,setTopup]=useState<{id:string;driver:string}|null>(null),[newTopup,setNewTopup]=useState(false),[topupDriver,setTopupDriver]=useState(""),[amount,setAmount]=useState(""),[method,setMethod]=useState(""),[reference,setReference]=useState(""),[notes,setNotes]=useState(""),[minimum,setMinimum]=useState(""),[commission,setCommission]=useState("");
  const canCustomers=permissions.includes("customers.view"),canPayments=permissions.includes("payments.view"),canManagePayments=permissions.includes("payments.manage"),canSettings=permissions.includes("settings.view"),canManageSettings=permissions.includes("settings.manage"),canManageMarketplace=permissions.includes("marketplace.manage");
  const qc=useQueryClient(); const invalidate=(...keys:string[])=>Promise.all(keys.map(key=>qc.invalidateQueries({queryKey:[key,projectId]})));
  const overview=useQuery({queryKey:["marketplace-overview",projectId],queryFn:()=>supabaseServices.marketplace.overview(projectId),refetchInterval:30_000});
  const jobs=useInfiniteQuery({queryKey:["marketplace-jobs",projectId,status,service],queryFn:({pageParam})=>supabaseServices.marketplace.listJobs(projectId,{status:status||undefined,serviceCode:service||undefined,limit:PAGE_SIZE,cursor:pageParam}),initialPageParam:null as null|{at:string;id:string},getNextPageParam:p=>p.nextCursor,enabled:tab==="trabajos"});
  const drivers=useInfiniteQuery({queryKey:["marketplace-drivers",projectId],queryFn:({pageParam})=>supabaseServices.marketplace.listDrivers(projectId,{limit:PAGE_SIZE,cursor:pageParam}),initialPageParam:null as null|{at:string;id:string},getNextPageParam:p=>p.nextCursor,enabled:tab==="conductores"});
  const customers=useInfiniteQuery({queryKey:["marketplace-customers",projectId],queryFn:({pageParam})=>supabaseServices.marketplace.listCustomers(projectId,{limit:PAGE_SIZE,cursor:pageParam}),initialPageParam:null as null|{at:string;id:string},getNextPageParam:p=>p.nextCursor,enabled:tab==="clientes"&&canCustomers});
  const wallets=useInfiniteQuery({queryKey:["marketplace-wallets",projectId],queryFn:({pageParam})=>supabaseServices.marketplace.listWallets(projectId,{limit:PAGE_SIZE,cursor:pageParam}),initialPageParam:null as null|{at:string;id:string},getNextPageParam:p=>p.nextCursor,enabled:tab==="billeteras"&&canPayments});
  const topups=useInfiniteQuery({queryKey:["marketplace-topups",projectId],queryFn:({pageParam})=>supabaseServices.marketplace.listTopups(projectId,{limit:PAGE_SIZE,cursor:pageParam}),initialPageParam:null as null|{at:string;id:string},getNextPageParam:p=>p.nextCursor,enabled:tab==="recargas"&&canPayments});
  const incidents=useInfiniteQuery({queryKey:["marketplace-incidents",projectId,incidentState],queryFn:({pageParam})=>supabaseServices.marketplace.listIncidents(projectId,{resolved:incidentState==="all"?undefined:incidentState==="resolved",limit:PAGE_SIZE,cursor:pageParam}),initialPageParam:null as null|{at:string;id:string},getNextPageParam:p=>p.nextCursor,enabled:tab==="incidencias"});
  const settings=useQuery({queryKey:["marketplace-financial-settings",projectId],queryFn:()=>supabaseServices.marketplace.financialSettings(projectId),enabled:tab==="configuracion"&&canSettings});
  const topupDrivers=useQuery({queryKey:["marketplace-topup-drivers",projectId],queryFn:()=>supabaseServices.marketplace.listDrivers(projectId,{limit:200}),enabled:newTopup});
  const detail=useQuery({queryKey:["marketplace-job-detail",projectId,jobId],queryFn:()=>supabaseServices.marketplace.getJobDetail(projectId,jobId!),enabled:!!jobId});
  useEffect(()=>{if(settings.data){setMinimum(String(settings.data.initialMinimumDeposit));setCommission(String(settings.data.commissionRate*100));}},[settings.data]);
  const suspend=useMutation({mutationFn:()=>supabaseServices.marketplace.setDriverSuspension(projectId,{userId:driver!.id,suspended:driver!.suspended,reason}),onSuccess:()=>{setDriver(null);setReason("");void invalidate("marketplace-overview","marketplace-drivers","marketplace-jobs","marketplace-incidents");},onError:e=>setError(errorText(e))});
  const resolve=useMutation({mutationFn:()=>supabaseServices.marketplace.resolveIncident(projectId,{jobId:incident!,resolution,note:reason,idempotencyKey:crypto.randomUUID()}),onSuccess:()=>{setIncident(null);setReason("");void invalidate("marketplace-overview","marketplace-jobs","marketplace-drivers","marketplace-incidents","marketplace-wallets");},onError:e=>setError(errorText(e))});
  const create=useMutation({mutationFn:()=>supabaseServices.marketplace.createTopup(projectId,{userId:topupDriver,amount:Number(amount),method,reference:reference||undefined,notes:notes||undefined,idempotencyKey:crypto.randomUUID()}),onSuccess:()=>{setNewTopup(false);setTopupDriver("");setAmount("");setMethod("");setReference("");setNotes("");void invalidate("marketplace-topups","marketplace-overview");},onError:e=>setError(errorText(e))});
  const confirm=useMutation({mutationFn:()=>supabaseServices.marketplace.confirmTopup(projectId,topup!.id,crypto.randomUUID()),onSuccess:()=>{setTopup(null);void invalidate("marketplace-topups","marketplace-wallets","marketplace-overview","marketplace-drivers");},onError:e=>setError(errorText(e))});
  const reject=useMutation({mutationFn:()=>supabaseServices.marketplace.rejectTopup(projectId,topup!.id,reason),onSuccess:()=>{setTopup(null);setReason("");void invalidate("marketplace-topups","marketplace-overview");},onError:e=>setError(errorText(e))});
  const save=useMutation({mutationFn:()=>supabaseServices.marketplace.updateFinancialSettings(projectId,{initialMinimumDeposit:Number(minimum),commissionRate:Number(commission)/100}),onSuccess:()=>void invalidate("marketplace-financial-settings"),onError:e=>setError(errorText(e))});
  const jobRows=rows(jobs),driverRows=rows(drivers),customerRows=rows(customers),walletRows=rows(wallets),topupRows=rows(topups),incidentRows=rows(incidents); const services=useMemo(()=>[...new Set(jobRows.map(x=>x.serviceCode))],[jobRows]);
  return <div className="space-y-5 sm:space-y-6"><ModuleHeader title="Trabajos" description="Operación de TukTuk Marketplace." icon={BriefcaseBusiness} module="pagos"/>
    <Tabs value={tab} onValueChange={setTab}><TabsList className="h-auto w-full flex-wrap justify-start"><TabsTrigger value="resumen">Resumen</TabsTrigger><TabsTrigger value="trabajos">Trabajos</TabsTrigger><TabsTrigger value="conductores">Conductores</TabsTrigger>{canCustomers&&<TabsTrigger value="clientes">Clientes</TabsTrigger>}{canPayments&&<><TabsTrigger value="billeteras">Billeteras</TabsTrigger><TabsTrigger value="recargas">Recargas</TabsTrigger></>}<TabsTrigger value="incidencias">Incidencias</TabsTrigger>{canSettings&&<TabsTrigger value="configuracion">Configuración</TabsTrigger>}</TabsList>
      <TabsContent value="resumen"><KpiGrid columns={4} density="compact">{[[ "Conductores",overview.data?.driversTotal,Users],[ "Activos",overview.data?.driversActive,Users],[ "En prueba",overview.data?.driversTrialActive,BriefcaseBusiness],[ "Post-prueba activos",overview.data?.driversPostTrialActive,WalletCards],[ "Trabajos publicados",overview.data?.jobsPublished,BriefcaseBusiness],[ "Trabajos activos",overview.data?.jobsActive,BriefcaseBusiness],[ "Incidencias abiertas",overview.data?.jobsIncidentOpen,AlertTriangle]].map(([name,value,Icon])=><MetricCard key={String(name)} label={String(name)} value={Number(value??0)} icon={Icon as typeof Users} module="pagos" isLoading={overview.isLoading}/>)}{!overview.isLoading&&overview.data?.pendingTopups!==null&&<MetricCard label="Recargas pendientes" value={overview.data?.pendingTopups??0} icon={WalletCards} module="pagos"/>}</KpiGrid></TabsContent>
      <TabsContent value="trabajos"><div className="mb-3 flex flex-wrap gap-2"><select value={status} onChange={e=>setStatus(e.target.value)} aria-label="Filtrar por estado"><option value="">Todos los estados</option>{["published","accepted","en_route","pickup","in_progress","completed","settled","incident","expired"].map(x=><option key={x} value={x}>{label(x)}</option>)}</select><select value={service} onChange={e=>setService(e.target.value)} aria-label="Filtrar por servicio"><option value="">Todos los servicios</option>{[...new Set([...services,"passenger","cargo","courier","tourism"])].map(x=><option key={x} value={x}>{label(x)}</option>)}</select></div><List title="Trabajos" query={jobs} empty="No hay trabajos.">{jobRows.map(x=><Row key={x.jobId} title={`${x.originText} → ${x.destinationText}`} detail={`${label(x.status)} · ${label(x.serviceCode)} · ${x.finalPrice} ${x.currency}${x.driverDisplayName?` · ${x.driverDisplayName}`:""}`} action={<Button size="sm" variant="outline" onClick={()=>setJobId(x.jobId)}>Ver detalle</Button>}/>)}</List></TabsContent>
      <TabsContent value="conductores"><List title="Conductores" query={drivers} empty="No hay conductores.">{driverRows.map(x=><Row key={x.userId} title={x.displayName} detail={`${x.phone??"Sin WhatsApp"} · ${label(x.status)} · ${x.vehicleName??"Sin vehículo"} · ${x.isAvailable?"Disponible":"No disponible"}`} action={canManageMarketplace?<Button size="sm" variant="outline" onClick={()=>setDriver({id:x.userId,suspended:x.status!=="suspended"})}>{x.status==="suspended"?"Reactivar":"Suspender"}</Button>:undefined}/>)}</List></TabsContent>
      {canCustomers&&<TabsContent value="clientes"><List title="Clientes" query={customers} empty="No hay clientes.">{customerRows.map(x=><Row key={x.customerId} title={x.displayName} detail={`${x.whatsappPhone} · ${x.jobsTotal} trabajos · ${x.jobsActive} activos · ${x.jobsSettled} liquidados`}/>)}</List></TabsContent>}
      {canPayments&&<><TabsContent value="billeteras"><List title="Billeteras" query={wallets} empty="No hay billeteras.">{walletRows.map(x=><Row key={x.userId} title={x.driverDisplayName} detail={`${x.totalBalance} ${x.currency} total · Real: ${x.realBalance} (${x.realAvailableBalance} disponible) · Promocional: ${x.promotionalBalance} (${x.promotionalAvailableBalance} disponible) · Reservado: ${x.realReservedBalance} real + ${x.promotionalReservedBalance} promocional`}/>)}</List></TabsContent><TabsContent value="recargas"><div className="mb-3">{canManagePayments&&<Button onClick={()=>setNewTopup(true)}>Registrar recarga</Button>}</div><List title="Recargas" query={topups} empty="No hay recargas.">{topupRows.map(x=><Row key={x.topupId} title={x.driverDisplayName} detail={`${x.amount} ${x.currency} · ${label(x.status)} · ${x.method}`} action={canManagePayments&&x.status==="requested"?<Button size="sm" onClick={()=>{setTopup({id:x.topupId,driver:x.driverDisplayName});setReason("");}}>Gestionar</Button>:undefined}/>)}</List></TabsContent></>}
      <TabsContent value="incidencias"><div className="mb-3 flex gap-2">{[["open","Abiertas"],["resolved","Resueltas"],["all","Todas"]].map(([id,name])=><Button key={id} size="sm" variant={incidentState===id?"default":"outline"} onClick={()=>setIncidentState(id)}>{name}</Button>)}</div><List title="Incidencias" query={incidents} empty="No hay incidencias.">{incidentRows.map(x=><Row key={x.jobId} title={label(x.serviceCode)} detail={`${x.incidentReason} · ${x.resolved?"Resuelta":"Abierta"}${x.driverDisplayName?` · ${x.driverDisplayName}`:""}`} action={canManageMarketplace&&!x.resolved?<Button size="sm" variant="outline" onClick={()=>{setIncident(x.jobId);setReason("");}}>Resolver</Button>:undefined}/>)}</List></TabsContent>
      {canSettings&&<TabsContent value="configuracion"><SectionCard title="Configuración financiera" module="pagos"><div className="space-y-3"><p className="text-sm text-text-secondary">Moneda: {settings.data?.walletCurrency??"CUP"}</p>{canManageSettings?<><Input type="number" min="0" step="0.01" value={minimum} onChange={e=>setMinimum(e.target.value)} placeholder="Depósito mínimo"/><Input type="number" min="0" max="100" step="0.01" value={commission} onChange={e=>setCommission(e.target.value)} placeholder="Comisión %"/><Button disabled={save.isPending||!minimum||!commission} onClick={()=>save.mutate()}>Guardar</Button></>:<p className="text-sm text-text-secondary">Depósito mínimo: {settings.data?.initialMinimumDeposit??"—"} · Comisión: {settings.data?`${settings.data.commissionRate*100}%`:"—"}</p>}</div></SectionCard></TabsContent>}
    </Tabs>{error&&<p className="text-sm text-destructive">{error}</p>}
    <Dialog open={!!jobId} onOpenChange={()=>setJobId(null)}><DialogContent><DialogHeader><DialogTitle>Detalle del trabajo</DialogTitle></DialogHeader>{detail.isLoading?"Cargando…":detail.data?<JobDetail detail={detail.data}/>:<p>No se encontró el trabajo.</p>}</DialogContent></Dialog>
    <Dialog open={!!driver} onOpenChange={()=>setDriver(null)}><DialogContent><DialogHeader><DialogTitle>{driver?.suspended?"Suspender conductor":"Reactivar conductor"}</DialogTitle></DialogHeader>{driver?.suspended&&<Textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="Motivo obligatorio"/>}<Button disabled={suspend.isPending||(driver?.suspended&&!reason.trim())} onClick={()=>suspend.mutate()}>{driver?.suspended?"Suspender":"Confirmar reactivación"}</Button></DialogContent></Dialog>
    <Dialog open={!!incident} onOpenChange={()=>setIncident(null)}><DialogContent><DialogHeader><DialogTitle>Resolver incidencia</DialogTitle></DialogHeader><div className="flex gap-2"><Button variant={resolution==="completed"?"default":"outline"} onClick={()=>setResolution("completed")}>Completar</Button><Button variant={resolution==="cancelled"?"default":"outline"} onClick={()=>setResolution("cancelled")}>Cancelar</Button></div><Textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="Motivo / nota de resolución"/><Button disabled={resolve.isPending||!reason.trim()} onClick={()=>resolve.mutate()}>Resolver</Button></DialogContent></Dialog>
    <Dialog open={newTopup} onOpenChange={setNewTopup}><DialogContent><DialogHeader><DialogTitle>Registrar recarga</DialogTitle></DialogHeader><select value={topupDriver} onChange={e=>setTopupDriver(e.target.value)} aria-label="Conductor"><option value="">Selecciona conductor</option>{topupDrivers.data?.items.map(x=><option key={x.userId} value={x.userId}>{x.displayName}</option>)}</select><Input type="number" min="0.01" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="Importe"/><Input value={method} onChange={e=>setMethod(e.target.value)} placeholder="Método"/><Input value={reference} onChange={e=>setReference(e.target.value)} placeholder="Referencia (opcional)"/><Textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Notas (opcional)"/><Button disabled={create.isPending||!topupDriver||Number(amount)<=0||!method.trim()} onClick={()=>create.mutate()}>Registrar</Button></DialogContent></Dialog>
    <Dialog open={!!topup} onOpenChange={()=>setTopup(null)}><DialogContent><DialogHeader><DialogTitle>Gestionar recarga de {topup?.driver}</DialogTitle></DialogHeader><Textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="Motivo obligatorio solo para rechazar"/><div className="flex gap-2"><Button disabled={confirm.isPending} onClick={()=>confirm.mutate()}>Confirmar</Button><Button variant="destructive" disabled={reject.isPending||!reason.trim()} onClick={()=>reject.mutate()}>Rechazar</Button></div></DialogContent></Dialog>
  </div>;
}
function List<T>({title,query,empty,children}:{title:string;query:{isLoading:boolean;data?:{pages:Array<{items:T[]}>};hasNextPage:boolean;isFetchingNextPage:boolean;fetchNextPage:()=>void};empty:string;children:React.ReactNode}) { const data=rows(query); return <SectionCard title={title} module="pagos" contentClassName="space-y-2">{query.isLoading?<p className="text-sm text-text-tertiary">Cargando…</p>:!data.length?<EmptyState icon={BriefcaseBusiness} title={empty} module="pagos"/>:<>{children}{query.hasNextPage&&<Button variant="outline" disabled={query.isFetchingNextPage} onClick={()=>query.fetchNextPage()}>{query.isFetchingNextPage?"Cargando…":"Cargar más"}</Button>}</>}</SectionCard>; }
function Row({title,detail,action}:{title:string;detail:string;action?:React.ReactNode}) { return <div className="flex items-center justify-between gap-3 rounded border border-border-subtle p-3"><div><p className="font-medium text-text-primary">{title}</p><p className="text-sm text-text-secondary">{detail}</p></div>{action??<Badge variant="secondary">—</Badge>}</div>; }
function JobDetail({detail}:{detail:import("@/lib/services/types").MarketplaceJobDetail}) { const {job,serviceRequest,assignment,customer,financial,timeline,incidentResolution}=detail; return <div className="space-y-3 text-sm"><p><b>Estado:</b> {label(text(job.status))}</p><p><b>Ruta:</b> {text(serviceRequest.origin_text)} → {text(serviceRequest.destination_text)}</p><p><b>Servicio:</b> {label(text(serviceRequest.service_code))} · Programado: {text(serviceRequest.scheduled_for)}</p>{customer&&<p><b>Cliente:</b> {text(customer.display_name)} · {text(customer.whatsapp_phone)}</p>}{assignment&&<p><b>Conductor / vehículo:</b> {text(assignment.driver_user_id)} · {text(assignment.vehicle_id)} · {label(text(assignment.billing_mode))}</p>}{financial&&<p><b>Finanzas:</b> {text(financial.amount)} {text(financial.currency)} · {label(text(financial.reservation_status))}</p>}{incidentResolution&&<p><b>Incidencia:</b> {label(text(incidentResolution.resolution))} · {text(incidentResolution.resolution_note)}</p>}<div><b>Timeline</b>{timeline.length?<ul className="mt-1 space-y-1">{timeline.map((e,i)=><li key={String(e.event_id??i)}>{text(e.created_at)} · {text(e.action)} · {label(text(e.from_status))} → {label(text(e.to_status))}{e.reason?` · ${text(e.reason)}`:""}</li>)}</ul>:<p className="mt-1 text-text-secondary">Sin eventos.</p>}</div></div>; }
