begin;
do $$
declare f text; relation_name text;
begin
  if not exists(select 1 from public.project_permissions where code='marketplace.view' and name='Ver operación de Trabajos' and category='marketplace') or not exists(select 1 from public.project_permissions where code='marketplace.manage' and name='Gestionar operación de Trabajos' and category='marketplace') then raise exception 'TEST_FAILED: marketplace permissions missing'; end if;
  if (select count(*) from public.project_role_permissions where permission_code='marketplace.view' and role_code in ('owner','admin','support','accounting'))<>4 or (select count(*) from public.project_role_permissions where permission_code='marketplace.manage' and role_code in ('owner','admin','support'))<>3 or exists(select 1 from public.project_role_permissions where permission_code like 'marketplace.%' and role_code='marketing') then raise exception 'TEST_FAILED: marketplace role matrix incorrect'; end if;
  if not exists(select 1 from pg_class where oid='public.marketplace_incident_resolutions'::regclass and relrowsecurity) or not exists(select 1 from pg_trigger where tgrelid='public.marketplace_incident_resolutions'::regclass and tgname='marketplace_incident_resolutions_immutable' and not tgisinternal) or not exists(select 1 from pg_trigger where tgrelid='public.marketplace_incident_resolutions'::regclass and tgname='audit_marketplace_incident_resolutions' and not tgisinternal) then raise exception 'TEST_FAILED: incident resolution security missing'; end if;
  foreach f in array array['public.admin_get_marketplace_overview(uuid)','public.admin_list_marketplace_drivers(uuid,integer,timestamptz,uuid)','public.admin_list_marketplace_jobs(uuid,text,text,integer,timestamptz,uuid)','public.admin_get_marketplace_job_detail(uuid,uuid)','public.admin_list_marketplace_customers(uuid,integer,timestamptz,uuid)','public.admin_list_marketplace_topups(uuid,text,integer,timestamptz,uuid)','public.admin_list_marketplace_wallets(uuid,integer,timestamptz,uuid)','public.admin_get_marketplace_financial_settings(uuid)','public.admin_list_marketplace_incidents(uuid,boolean,integer,timestamptz,uuid)','public.admin_resolve_marketplace_incident(uuid,uuid,text,text,uuid)','public.admin_set_marketplace_driver_suspension(uuid,uuid,boolean,text)'] loop
    if to_regprocedure(f) is null then raise exception 'TEST_FAILED: missing %',f; end if;
    if has_function_privilege('anon',f,'execute') or not has_function_privilege('authenticated',f,'execute') then raise exception 'TEST_FAILED: grants invalid for %',f; end if;
    select lower(pg_get_functiondef(f::regprocedure)) into relation_name; if relation_name not like '%security definer%' or relation_name not like '%set search_path = ''''%' then raise exception 'TEST_FAILED: hardening missing for %',f; end if;
  end loop;
  select lower(pg_get_functiondef('public.admin_resolve_marketplace_incident(uuid,uuid,text,text,uuid)'::regprocedure)) into f;
  if position('from public.jobs' in f)>position('from public.job_assignments' in f) or position('from public.job_assignments' in f)>position('from public.wallets' in f) or position('from public.wallets' in f)>position('from public.commission_reservations' in f) or f not like '%trial_free%' or f not like '%job_commission_reversal%' or f not like '%incident_resolved%' or f not like '%status<>''incident''%' then raise exception 'TEST_FAILED: incident resolution contract incomplete'; end if;
  if exists(select 1 from information_schema.role_table_grants where table_schema='public' and table_name in ('driver_profiles','vehicles','customers','service_requests','jobs','job_events','job_assignments','wallets','topups','wallet_transactions','commission_reservations','marketplace_work_trials','marketplace_customer_sessions','marketplace_incident_resolutions') and grantee in ('anon','authenticated') and privilege_type='SELECT') then raise exception 'TEST_FAILED: direct sensitive table select grant'; end if;
end $$;
-- Dynamic scenarios pending: RBAC role matrix; lists with/without secondary permissions; cursors;
-- suspend/reactivate; active trial during suspension; trial/wallet incident paths; retries/concurrency;
-- availability restoration; and PII/token non-disclosure must be exercised against an isolated fixture database.
rollback;
