import { demoServices } from "./demo";
import { supabaseServices } from "./supabase";
import type { AdminServices, DataProvider } from "./types";

export type {
  AdminServices,
  Currency,
  DataProvider,
  LicenseAuditLogService,
  LicenseAuditEntry,
  LicenseDevice,
  CreateLicenseInput,
  LicensePlan,
  LicenseBillingInput,
  LicenseService,
  LicenseStatus,
  LicenseType,
  LicenseValidationResult,
  PaymentService,
  ProjectPermission,
  ProjectRole,
  ProjectSettings,
  WhatsAppSettings,
  AuditEvent,
  AuditService,
  ProjectMemberService,
  ProjectService,
  ServiceClient,
  ServiceLicense,
  ServicePayment,
  UpdatePaymentInput,
  BillingPreview,
  BillingReceipt,
  ChargePlanInput,
  RetentionMetrics,
  UsageAnalyticsDay,
  UsageAnalyticsDimensions,
  UsageAnalyticsFilters,
  UsageAnalyticsService,
  CommercialLead,
  CommercialLeadInput,
  CommercialLeadStatus,
  CommercialSource,
  CommercialCampaign,
  CommercialLeadHistoryEntry,
  CommercialMetrics,
  CommercialService,
  PreinvoiceStatus,
  ExchangeRateMode,
  ReferralRewardStatus,
  P0ASettings,
  ExchangeRateHistoryEntry,
  DocumentIdentitySnapshot,
  Preinvoice,
  CreatePreinvoiceInput,
  PreinvoiceConfirmationPreview,
  ConfirmPreinvoicePaymentInput,
  P0AFoundationService,
  Client360,
  Client360Activity,
  Client360Device,
  Client360Payment,
  Client360Preinvoice,
  Client360ReferralPerson,
  Client360Service,
  ClientReferralSummary,
  ReferralOverviewRow,
  ReferralOverview,
  ReferralQualificationMode,
  ReferralCampaignStatus,
  ReferralCampaign,
  StartReferralCampaignInput,
  ReferralService,
  MobileAnnouncementCategory,
  MobilePushAudience,
  SendMobileAnnouncementInput,
  MobileAnnouncementResult,
  MobileCommunicationService,
  MarketplaceAdminService,
  MarketplaceOverview,
  MarketplaceDriver,
  MarketplaceDriver360,
  MarketplaceDriverFinancial360,
  MarketplaceJob,
  MarketplaceJobDetail,
  MarketplaceCustomer,
  MarketplaceCustomer360,
  MarketplaceCustomerHistoryItem,
  MarketplaceTopup,
  MarketplacePaymentMethod,
  MarketplaceFinancialDocument,
  MarketplaceWallet,
  MarketplaceFinancialSettings,
  MarketplaceDispatchSettings,
  MarketplaceDispatchSettingsInput,
  MarketplaceIncident,
  MarketplaceIncidentResolution,
  MarketplacePricingTariff,
  MarketplacePricingTariffInput,
  MarketplacePricingAdjustment,
} from "./types";

export function getAdminServices(provider: DataProvider = "supabase"): AdminServices {
  return provider === "supabase" ? supabaseServices : demoServices;
}

export { demoServices, supabaseServices };
