/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminProyectosIndexRouteImport } from './routes/admin.proyectos.index'
import { Route as AdminProyectosIdRouteImport } from './routes/admin.proyectos.$id'
import { Route as AdminProyectosIdIndexRouteImport } from './routes/admin.proyectos.$id.index'
import { Route as AdminProyectosIdSectionRouteImport } from './routes/admin.proyectos.$id.$section'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProyectosIndexRoute = AdminProyectosIndexRouteImport.update({
  id: '/proyectos/',
  path: '/proyectos/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProyectosIdRoute = AdminProyectosIdRouteImport.update({
  id: '/proyectos/$id',
  path: '/proyectos/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProyectosIdIndexRoute = AdminProyectosIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminProyectosIdRoute,
} as any)
const AdminProyectosIdSectionRoute = AdminProyectosIdSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => AdminProyectosIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/proyectos/$id': typeof AdminProyectosIdRouteWithChildren
  '/admin/proyectos/': typeof AdminProyectosIndexRoute
  '/admin/proyectos/$id/$section': typeof AdminProyectosIdSectionRoute
  '/admin/proyectos/$id/': typeof AdminProyectosIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin': typeof AdminIndexRoute
  '/admin/proyectos': typeof AdminProyectosIndexRoute
  '/admin/proyectos/$id/$section': typeof AdminProyectosIdSectionRoute
  '/admin/proyectos/$id': typeof AdminProyectosIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/proyectos/$id': typeof AdminProyectosIdRouteWithChildren
  '/admin/proyectos/': typeof AdminProyectosIndexRoute
  '/admin/proyectos/$id/$section': typeof AdminProyectosIdSectionRoute
  '/admin/proyectos/$id/': typeof AdminProyectosIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/login'
    | '/admin/'
    | '/admin/proyectos/$id'
    | '/admin/proyectos/'
    | '/admin/proyectos/$id/$section'
    | '/admin/proyectos/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/login'
    | '/admin'
    | '/admin/proyectos'
    | '/admin/proyectos/$id/$section'
    | '/admin/proyectos/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/login'
    | '/admin/'
    | '/admin/proyectos/$id'
    | '/admin/proyectos/'
    | '/admin/proyectos/$id/$section'
    | '/admin/proyectos/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/proyectos/': {
      id: '/admin/proyectos/'
      path: '/proyectos'
      fullPath: '/admin/proyectos/'
      preLoaderRoute: typeof AdminProyectosIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/proyectos/$id': {
      id: '/admin/proyectos/$id'
      path: '/proyectos/$id'
      fullPath: '/admin/proyectos/$id'
      preLoaderRoute: typeof AdminProyectosIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/proyectos/$id/': {
      id: '/admin/proyectos/$id/'
      path: '/'
      fullPath: '/admin/proyectos/$id/'
      preLoaderRoute: typeof AdminProyectosIdIndexRouteImport
      parentRoute: typeof AdminProyectosIdRoute
    }
    '/admin/proyectos/$id/$section': {
      id: '/admin/proyectos/$id/$section'
      path: '/$section'
      fullPath: '/admin/proyectos/$id/$section'
      preLoaderRoute: typeof AdminProyectosIdSectionRouteImport
      parentRoute: typeof AdminProyectosIdRoute
    }
  }
}

interface AdminProyectosIdRouteChildren {
  AdminProyectosIdSectionRoute: typeof AdminProyectosIdSectionRoute
  AdminProyectosIdIndexRoute: typeof AdminProyectosIdIndexRoute
}

const AdminProyectosIdRouteChildren: AdminProyectosIdRouteChildren = {
  AdminProyectosIdSectionRoute: AdminProyectosIdSectionRoute,
  AdminProyectosIdIndexRoute: AdminProyectosIdIndexRoute,
}

const AdminProyectosIdRouteWithChildren =
  AdminProyectosIdRoute._addFileChildren(AdminProyectosIdRouteChildren)

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminProyectosIdRoute: typeof AdminProyectosIdRouteWithChildren
  AdminProyectosIndexRoute: typeof AdminProyectosIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminProyectosIdRoute: AdminProyectosIdRouteWithChildren,
  AdminProyectosIndexRoute: AdminProyectosIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
